ci(gh-tem): shared template
hexonet/whmcs-ispapi-helper pull request #14
Opened 2021-05-17 11:53 UTC by Rashad-j

2021-05-17 13:27 UTC, papakai requested changes

2021-05-17 13:27 UTC, papakai commented on .github/workflows/whmcs.yml
> -        run: phpcs --standard=PSR12 -q -n --colors --extensions=php,inc,lib --ignore=sdk,node_modules,vendor,templates_c .
Important to keep the `sdk` folder in the ignore setting. Please add it to the main shared `whmcs` template too.
thanks!

2021-05-17 14:04 UTC, Rashad-j commented on .github/workflows/whmcs.yml
> -        run: phpcs --standard=PSR12 -q -n --colors --extensions=php,inc,lib --ignore=sdk,node_modules,vendor,templates_c .
Added to the main template & changed here

2021-05-18 09:21 UTC, papakai approved these changes
ty

2021-05-18 09:22 UTC, merged